### ISSUE TITLE
Call for this paper

### ISSUE THREAD

**Issue by moguiyan1992** [giswqs/Wetland-Hydro-GEE#1]
Dear Teacher Wu:
        Can you share this paper titled "Integrating LiDAR data and multi-temporal aerial imagery to map wetland inundation dynamics using Google Earth Engine"? Thank you!
  
                                                                                                                                         Guiyan Mo
                                                                                                                 G-mail:guiyan.mo@hotmail.com

**Comment by giswqs** [comment]
You can download it from this [link](https://www.researchgate.net/publication/334142000_Integrating_LiDAR_data_and_multi-temporal_aerial_imagery_to_map_wetland_inundation_dynamics_using_Google_Earth_Engine).

**Comment by moguiyan1992** [comment]
Okay, i get it ! Thanks again. Looking forward to your next lecture in Geoinsider.
